### ISSUE TITLE
How to lauch the app

### ISSUE THREAD

**Issue by nsilverio** [mwasiluk/angular-surveys#13]
Hello
I am new to Angular and I tried to launch the app using npm install / npm start but it did not work. I could not found further details on the readme file.
I appreciate your help
Thank you

**Comment by mwasiluk** [comment]
Hi
Demos should work after running `npm install` and `bower install` in root git clone directory.
To see bootstrap demo open demo/demo.html 
Material design demo is in demo-material/demo.html

If you want to add surveys to your app, run:
`bower install angular-surveys --save`
Then you need to include dependencies and survey module's  css and js files like in the demo.

Available directives are described here https://github.com/mwasiluk/angular-surveys/wiki/Directives

Hope this helps.

**Comment by nsilverio** [comment]
Hello 
npm and bower and install was the commands that I tried but I could not launch the app accessing demo directory on my browser. 
Is there any specific command for gulp? 
Thank you

**Comment by mwasiluk** [comment]
Hi,
It turned out that there was a problem with a bower dependency Sortable;  ng-sortable directive was removed from the lib and was moved to https://github.com/SortableJS/angular-legacy-sortablejs. 
I've added this file to the 'vendor' directory.
The demo should work now. Let me know if there are any more issues.
Thanks

**Comment by nsilverio** [comment]
Hello
Thanks for your previous reply. I followed the same instructions after cloning the project again and I still can't launch the application. 
I'm afraid I should run some commands for making gulp start but I am not familiar with these, but for grunt I would run grunt serve --force and then opening the app on my browser. Could you provide me a detailed list of steps you are following to run the app locally?

Thank you

**Comment by donlinmi** [comment]
Hi nsilverio,

I just started playing with angular-surveys and had the same issue. Here are the steps I followed to get the demo working:

1) cloned repo
2) ran 'bower install angular-surveys --save' in base directory
3) copied ~/vendor/angular-legacy-sortable.js to ~/bower_components/Sortable/ and renamed the file to ng-sortable.js
4) Run demo?
    - You have to run the demo on your local webserver, and in my case I had to add the JSON MIME type to my IIS config, as the demo *.json files weren't loading in the stock ASP.NET project I created for running the demo

Good luck!

**Comment by mwasiluk** [comment]
Hi all, 
If you have cloned the angular-surveys repository, then this steps should be enough:
1. `npm install` in cloned project root
2. `bower install` in cloned project root
3.a open demo/demo.html with local server, eg if you're using intellij idea: mouse right click on demo/demo.html -> 'Run demo.html'
3.b OR run `gulp serve` or `gulp serve-bootstrap`; It should open the demo page in your default browser. It will also watch for changes in surveys source and will refresh page automatically after rebuilding dist.

**Comment by nsilverio** [comment]
Hello everyone
I managed to run the demo using 
```
npm install
bower install 
gulp serve 
```

Thank you all for the support. I am now trying to figure ou which files should be transferred to to my remote server in order to have the demo working and also the correct gulp task to generate the files. Could anyone advise?

Cheers

**Comment by sunil233** [comment]
Failed to instantiate module ng-sortable due to:

Error: [$injector:nomod] Module 'ng-sortable' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

![image](https://cloud.githubusercontent.com/assets/16982511/23095483/588e617e-f5d8-11e6-9a86-5457fbc7ee92.png)

**Comment by mohammadamer** [comment]
Sorry I am new how to open this project using visual studio...?

**Comment by nishanc** [comment]
@mwasiluk It is better if you can create a tutorial on how to built this kind of an application, or just a demonstration on how to integrate this library to a back end. Never the less, awesome work you have done here.

**Comment by srikanth-vanga-pipra** [comment]
how to integreated angular 8 project . and how to create the internal linkes and material designes
please tell me.
